/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export declare namespace DPlaceGrid {
  export type PixelStruct = {
    contested: BigNumberish;
    lastUpdateTime: BigNumberish;
    purchasePrice: BigNumberish;
    owner: string;
  };

  export type PixelStructOutput = [number, BigNumber, BigNumber, string] & {
    contested: number;
    lastUpdateTime: BigNumber;
    purchasePrice: BigNumber;
    owner: string;
  };
}

export interface DPlaceGridInterface extends utils.Interface {
  functions: {
    "basePrice()": FunctionFragment;
    "calculatePixelPrice(uint256,uint256)": FunctionFragment;
    "calculatePixelsPrice(uint256[],uint256[])": FunctionFragment;
    "claimPixel(uint256,uint256,bytes)": FunctionFragment;
    "claimPixels(uint256[],uint256[],bytes[])": FunctionFragment;
    "deposits(address)": FunctionFragment;
    "getPixel(uint256,uint256)": FunctionFragment;
    "grid(uint256,uint256)": FunctionFragment;
    "gridSize()": FunctionFragment;
    "initialize(uint256,uint256,uint256,uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "priceDecayInterval()": FunctionFragment;
    "priceVelocity()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setBasePrice(uint256)": FunctionFragment;
    "setGridSize(uint256)": FunctionFragment;
    "setPriceVelocity(uint256)": FunctionFragment;
    "setpPriceDecayInterval(uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "withdraw()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "basePrice"
      | "calculatePixelPrice"
      | "calculatePixelsPrice"
      | "claimPixel"
      | "claimPixels"
      | "deposits"
      | "getPixel"
      | "grid"
      | "gridSize"
      | "initialize"
      | "owner"
      | "priceDecayInterval"
      | "priceVelocity"
      | "renounceOwnership"
      | "setBasePrice"
      | "setGridSize"
      | "setPriceVelocity"
      | "setpPriceDecayInterval"
      | "transferOwnership"
      | "withdraw"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "basePrice", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "calculatePixelPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculatePixelsPrice",
    values: [BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claimPixel",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimPixels",
    values: [BigNumberish[], BigNumberish[], BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "deposits", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getPixel",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grid",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "gridSize", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "priceDecayInterval",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "priceVelocity",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBasePrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setGridSize",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPriceVelocity",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setpPriceDecayInterval",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(functionFragment: "basePrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculatePixelPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculatePixelsPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimPixel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimPixels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposits", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPixel", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "grid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gridSize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceDecayInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "priceVelocity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBasePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGridSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPriceVelocity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setpPriceDecayInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "Initialized(uint8)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "PixelChanged(uint256,uint256,address,bytes,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PixelChanged"): EventFragment;
}

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PixelChangedEventObject {
  x: BigNumber;
  y: BigNumber;
  owner: string;
  data: string;
  price: BigNumber;
}
export type PixelChangedEvent = TypedEvent<
  [BigNumber, BigNumber, string, string, BigNumber],
  PixelChangedEventObject
>;

export type PixelChangedEventFilter = TypedEventFilter<PixelChangedEvent>;

export interface DPlaceGrid extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DPlaceGridInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    basePrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    calculatePixelPrice(
      x: BigNumberish,
      y: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    calculatePixelsPrice(
      x: BigNumberish[],
      y: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    claimPixel(
      x: BigNumberish,
      y: BigNumberish,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    claimPixels(
      x: BigNumberish[],
      y: BigNumberish[],
      data: BytesLike[],
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    deposits(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    getPixel(
      x: BigNumberish,
      y: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[DPlaceGrid.PixelStructOutput]>;

    grid(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [number, BigNumber, BigNumber, string] & {
        contested: number;
        lastUpdateTime: BigNumber;
        purchasePrice: BigNumber;
        owner: string;
      }
    >;

    gridSize(overrides?: CallOverrides): Promise<[BigNumber]>;

    initialize(
      _basePrice: BigNumberish,
      _priceDecayInterval: BigNumberish,
      _priceVelocity: BigNumberish,
      _gridSize: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    priceDecayInterval(overrides?: CallOverrides): Promise<[BigNumber]>;

    priceVelocity(overrides?: CallOverrides): Promise<[BigNumber]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setBasePrice(
      _basePrice: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setGridSize(
      _gridSize: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setPriceVelocity(
      _priceVelocity: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setpPriceDecayInterval(
      _priceDecayInterval: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    withdraw(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  basePrice(overrides?: CallOverrides): Promise<BigNumber>;

  calculatePixelPrice(
    x: BigNumberish,
    y: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  calculatePixelsPrice(
    x: BigNumberish[],
    y: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  claimPixel(
    x: BigNumberish,
    y: BigNumberish,
    data: BytesLike,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  claimPixels(
    x: BigNumberish[],
    y: BigNumberish[],
    data: BytesLike[],
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  deposits(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  getPixel(
    x: BigNumberish,
    y: BigNumberish,
    overrides?: CallOverrides
  ): Promise<DPlaceGrid.PixelStructOutput>;

  grid(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [number, BigNumber, BigNumber, string] & {
      contested: number;
      lastUpdateTime: BigNumber;
      purchasePrice: BigNumber;
      owner: string;
    }
  >;

  gridSize(overrides?: CallOverrides): Promise<BigNumber>;

  initialize(
    _basePrice: BigNumberish,
    _priceDecayInterval: BigNumberish,
    _priceVelocity: BigNumberish,
    _gridSize: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  priceDecayInterval(overrides?: CallOverrides): Promise<BigNumber>;

  priceVelocity(overrides?: CallOverrides): Promise<BigNumber>;

  renounceOwnership(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setBasePrice(
    _basePrice: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setGridSize(
    _gridSize: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setPriceVelocity(
    _priceVelocity: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setpPriceDecayInterval(
    _priceDecayInterval: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  withdraw(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    basePrice(overrides?: CallOverrides): Promise<BigNumber>;

    calculatePixelPrice(
      x: BigNumberish,
      y: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculatePixelsPrice(
      x: BigNumberish[],
      y: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimPixel(
      x: BigNumberish,
      y: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimPixels(
      x: BigNumberish[],
      y: BigNumberish[],
      data: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    deposits(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    getPixel(
      x: BigNumberish,
      y: BigNumberish,
      overrides?: CallOverrides
    ): Promise<DPlaceGrid.PixelStructOutput>;

    grid(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [number, BigNumber, BigNumber, string] & {
        contested: number;
        lastUpdateTime: BigNumber;
        purchasePrice: BigNumber;
        owner: string;
      }
    >;

    gridSize(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _basePrice: BigNumberish,
      _priceDecayInterval: BigNumberish,
      _priceVelocity: BigNumberish,
      _gridSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    priceDecayInterval(overrides?: CallOverrides): Promise<BigNumber>;

    priceVelocity(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setBasePrice(
      _basePrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setGridSize(
      _gridSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setPriceVelocity(
      _priceVelocity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setpPriceDecayInterval(
      _priceDecayInterval: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "PixelChanged(uint256,uint256,address,bytes,uint256)"(
      x?: null,
      y?: null,
      owner?: null,
      data?: null,
      price?: null
    ): PixelChangedEventFilter;
    PixelChanged(
      x?: null,
      y?: null,
      owner?: null,
      data?: null,
      price?: null
    ): PixelChangedEventFilter;
  };

  estimateGas: {
    basePrice(overrides?: CallOverrides): Promise<BigNumber>;

    calculatePixelPrice(
      x: BigNumberish,
      y: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculatePixelsPrice(
      x: BigNumberish[],
      y: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimPixel(
      x: BigNumberish,
      y: BigNumberish,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    claimPixels(
      x: BigNumberish[],
      y: BigNumberish[],
      data: BytesLike[],
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    deposits(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    getPixel(
      x: BigNumberish,
      y: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grid(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    gridSize(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _basePrice: BigNumberish,
      _priceDecayInterval: BigNumberish,
      _priceVelocity: BigNumberish,
      _gridSize: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    priceDecayInterval(overrides?: CallOverrides): Promise<BigNumber>;

    priceVelocity(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setBasePrice(
      _basePrice: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setGridSize(
      _gridSize: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setPriceVelocity(
      _priceVelocity: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setpPriceDecayInterval(
      _priceDecayInterval: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    withdraw(overrides?: Overrides & { from?: string }): Promise<BigNumber>;
  };

  populateTransaction: {
    basePrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    calculatePixelPrice(
      x: BigNumberish,
      y: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculatePixelsPrice(
      x: BigNumberish[],
      y: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claimPixel(
      x: BigNumberish,
      y: BigNumberish,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    claimPixels(
      x: BigNumberish[],
      y: BigNumberish[],
      data: BytesLike[],
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    deposits(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPixel(
      x: BigNumberish,
      y: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grid(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    gridSize(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      _basePrice: BigNumberish,
      _priceDecayInterval: BigNumberish,
      _priceVelocity: BigNumberish,
      _gridSize: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    priceDecayInterval(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    priceVelocity(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setBasePrice(
      _basePrice: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setGridSize(
      _gridSize: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setPriceVelocity(
      _priceVelocity: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setpPriceDecayInterval(
      _priceDecayInterval: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    withdraw(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
